import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MenuButton from "./menuButton"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex box-border h-20 bg-white border-b-2">
              <div className="mt-5 ml-5 text-2xl md:ml-10 md:text-lg lg:ml-10 lg:text-5xl">
                <h1>StShoot</h1>
              </div>
              <div className="ml-auto">
                <MenuButton />
              </div>
            </div>
        {children}
      </body>
    </html>
  );
}
